# 277_TOPIC_max_length_line_boundary_510.spec
# Tests TOPIC with maximum allowed IRC input line boundary (exactly 510 characters before \r\n).
# Expected: Server accepts the line without dropping or crashing and stores topic properly.
CLIENTS C1

C1 SEND PASS 1234
C1 SEND NICK Alice
C1 SEND USER alice 0 * :Alice
C1 EXPECT 001 Alice :*
C1 SEND JOIN #boundary
C1 EXPECT :Alice!* JOIN #boundary
C1 EXPECT 331 Alice #boundary :*
C1 EXPECT 353 Alice = #boundary :*
C1 EXPECT 366 Alice #boundary :*

# Payload of 493 characters + command header (17 chars) = exactly 510 chars (exceeds topic length limit of 150)
C1 SEND TOPIC #boundary :AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C1 EXPECT 461 Alice TOPIC :Topic length is too long
