# Validates bare LF termination, whitespace tolerance, 512-byte buffers, and mid-stream disconnect handling.
CLIENTS C1, C2

# NET-05: Leading whitespace, extra spaces between params, and empty lines (\r\n\r\n)
C1 SEND_RAW \r\n\r\n   PASS   1234   \r\n
C1 SEND_RAW    NICK   AliceLF   \r\n

# NET-02: Unix bare LF (\n) line ending without \r
C1 SEND_RAW USER alice 0 * :Alice LF\n
C1 EXPECT 001 AliceLF :*

# NET-06: 512-byte boundary resilience (send long 550-byte PRIVMSG payload without crashing server)
C1 SEND_RAW PRIVMSG AliceLF :AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n
C1 EXPECT_CONNECTED

# NET-09: Client C2 sends half a command and disconnects abruptly (RST)
C2 SEND_RAW NICK PartialNic
C2 RESET
C2 EXPECT_DISCONNECT

# Verify C1 is unharmed and C2 can reconnect and register cleanly
C1 EXPECT_CONNECTED
C2 RECONNECT
C2 SEND PASS 1234
C2 SEND NICK BobNet
C2 SEND USER bob 0 * :Bob Net
C2 EXPECT 001 BobNet :*
C2 EXPECT_CONNECTED
